import React, { useState } from "react";
import { useLanguage } from "../../contexts/LanguageContext";
import { motion, AnimatePresence } from "framer-motion";
import {
  User,
  Mail,
  Lock,
  Eye,
  EyeOff,
  ArrowRight,
  AlertCircle,
  ShieldCheck,
  TrendingUp,
  TrendingDown,
  Globe,
  Activity
} from "lucide-react";
import { supabase } from "../../lib/supabase";
import { useAuth, type Profile } from "../../contexts/AuthContext";
import logoImg from "../../assets/Logo-url.png";
import btcLogo from "../../assets/icon/Bitcoin.png";
import ethLogo from "../../assets/icon/Ethereum.png";
import goldLogo from "../../assets/icon/Gold.png";

// Dummy market data for the right side
const MARKET_DATA = [
  { symbol: "BTC/USD", name: "Bitcoin", icon: btcLogo, price: "68,432.10", change: "+4.2%", isUp: true, points: "0,50 10,40 20,45 30,30 40,35 50,20 60,25 70,10 80,15 90,5 100,0" },
  { symbol: "ETH/USD", name: "Ethereum", icon: ethLogo, price: "3,840.50", change: "-1.1%", isUp: false, points: "0,10 10,15 20,8 30,12 40,20 50,18 60,30 70,25 80,35 90,40 100,50" },
  { symbol: "XAU/USD", name: "Gold", icon: goldLogo, price: "2,340.20", change: "+0.8%", isUp: true, points: "0,30 10,25 20,28 30,22 40,15 50,18 60,10 70,12 80,5 90,8 100,0" },
];

export const AuthForms: React.FC = () => {
  const { t, language, setLanguage } = useLanguage();
  const { login } = useAuth();

  const [isLogin, setIsLogin] = useState(true);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");

  // Form State
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [email, setEmail] = useState("");
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");

  // Handle Form Submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg("");
    setLoading(true);

    try {
      if (isLogin) {
        // Login flow
        const { data, error } = await supabase
          .from("profiles")
          .select("*")
          .eq("username", username)
          .eq("password", password) // Assuming plain text lookup as instructed
          .single();

        if (error || !data) {
          throw new Error("Invalid username or password.");
        }

        login(data as Profile);
      } else {
        // Register flow
        if (password !== confirmPassword) {
          throw new Error("Passwords do not match.");
        }

        // Check for existing username or email
        const { data: existingUsers, error: checkError } = await supabase
          .from("profiles")
          .select("username, email")
          .or(`username.eq.${username},email.eq.${email}`);

        if (checkError) {
          throw new Error("Error checking for duplicates. Please try again.");
        }

        if (existingUsers && existingUsers.length > 0) {
          const hasUsername = existingUsers.some((u) => u.username === username);
          const hasEmail = existingUsers.some((u) => u.email === email);

          if (hasUsername) {
            throw new Error("This username is already taken.");
          }
          if (hasEmail) {
            throw new Error("This email is already registered.");
          }
        }

        // Let's create a new uuid directly if needed or use supabase auth's id,
        // but since we are not using supabase auth we can insert with generated id.
        // Usually UUID is generated by the DB default.
        const { data, error } = await supabase
          .from("profiles")
          .insert([
            {
              id: crypto.randomUUID(),
              username,
              first_name: firstName,
              last_name: lastName,
              email,
              password,
              balance: 0,
            }
          ])
          .select()
          .single();

        if (error) {
          if (error.code === '23505') { // Unique violation fallback
            throw new Error("User with that username or email already exists.");
          }
          throw error;
        }

        if (data) {
          login(data as Profile);
        }
      }
    } catch (err) {
      const error = err as Error;
      setErrorMsg(error.message || "An error occurred.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background flex flex-col relative overflow-hidden font-sans text-slate-100">
      {/* Background Ambience */}
      <div className="fixed top-[-10%] right-[-5%] w-[600px] h-[600px] bg-primary/20 rounded-full blur-[150px] animate-pulse pointer-events-none" />
      <div className="fixed bottom-[-10%] left-[-10%] w-[600px] h-[600px] bg-accent/20 rounded-full blur-[150px] animate-pulse pointer-events-none" style={{ animationDelay: '2s' }} />

      {/* Header Navbar */}
      <header className="relative z-50 w-full px-8 py-6 flex items-center justify-between border-b border-white/5 bg-background/50 backdrop-blur-xl">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl overflow-hidden shadow-lg shadow-primary/30">
            <img src={logoImg} alt="MetaStock Config" className="w-full h-full object-cover" />
          </div>
          <span className="text-xl font-black tracking-tight text-white">MetaStock</span>
        </div>
        <div className="flex flex-row gap-4">
          {/* <div className="hidden md:flex items-center gap-6 text-sm font-semibold text-slate-400">
            <span onClick={() => navigate("/market")} className="hover:text-white cursor-pointer transition-colors">{t("markets") || "Markets"}</span>
            <span onClick={() => navigate("/trade")} className="hover:text-white cursor-pointer transition-colors">{t("trade") || "Trade"}</span>
            <span onClick={() => navigate("/platform")} className="hover:text-white cursor-pointer transition-colors">{t("platform") || "Platform"}</span>
          </div> */}
          <button
            onClick={() => setLanguage(language === "th" ? "en" : "th")}
            className="flex items-center gap-2 justify-center px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:bg-white/10 hover:text-white transition-colors group"
          >
            <Globe size={16} className="group-hover:rotate-180 transition-transform duration-700" />
            <span className="text-xs font-medium">{language === "th" ? "EN" : "ไทย"}</span>
          </button>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col sm:flex-row w-full max-w-7xl mx-auto z-10 relative">

        {/* Left Side: Auth Forms */}
        <section className="w-full lg:w-1/2 flex items-center justify-center p-6 lg:p-12 ">
          <motion.div
            layout
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ type: "spring", damping: 25, stiffness: 120 }}
            className="w-full max-w-md relative"
          >
            <div className="glass-card shadow-2xl shadow-primary/10 border border-white/10 bg-slate-900/60 backdrop-blur-2xl p-8 rounded-3xl relative overflow-hidden">
              <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-primary to-accent" />

              <div className="text-center mb-8">
                <h1 className="text-3xl font-black text-white mb-2 tracking-tight">
                  {isLogin ? (t("login") || "Welcome Back") : (t("register") || "Create Account")}
                </h1>
                <p className="text-slate-400 text-sm font-medium">
                  {isLogin ? "Enter your credentials to access the terminal" : "Join the next generation of professional trading"}
                </p>
              </div>

              <form className="space-y-4" onSubmit={handleSubmit}>
                <AnimatePresence>
                  {errorMsg && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      className="overflow-hidden"
                    >
                      <div className="p-3 mb-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-500 text-sm font-semibold flex items-center gap-2">
                        <AlertCircle size={16} />
                        <span>{errorMsg}</span>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                <div className="space-y-4">
                  <AuthInput
                    icon={<User size={18} />}
                    placeholder={t("username") || "Username"}
                    type="text"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    required
                  />

                  <AnimatePresence>
                    {!isLogin && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="space-y-4 overflow-hidden"
                      >
                        <div className="flex gap-4">
                          <AuthInput
                            icon={<User size={18} />}
                            placeholder="First Name"
                            type="text"
                            value={firstName}
                            onChange={(e) => setFirstName(e.target.value)}
                            required
                          />
                          <AuthInput
                            icon={<User size={18} />}
                            placeholder="Last Name"
                            type="text"
                            value={lastName}
                            onChange={(e) => setLastName(e.target.value)}
                            required
                          />
                        </div>

                        <AuthInput
                          icon={<Mail size={18} />}
                          placeholder={t("email") || "Email"}
                          type="email"
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                          required
                        />
                      </motion.div>
                    )}
                  </AnimatePresence>

                  {/* Password */}
                  <div className="relative">
                    <AuthInput
                      icon={<Lock size={18} />}
                      placeholder={t("password") || "Password"}
                      type={showPassword ? "text" : "password"}
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      required
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white transition-colors"
                      style={{ height: '100%', alignContent: 'center', backgroundColor: 'transparent' }}
                    >
                      {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                    </button>
                  </div>

                  {/* Confirm Password — Register only */}
                  <AnimatePresence>
                    {!isLogin && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="relative overflow-hidden"
                      >
                        <AuthInput
                          icon={<ShieldCheck size={18} />}
                          placeholder="Confirm Password"
                          type={showConfirmPassword ? "text" : "password"}
                          value={confirmPassword}
                          onChange={(e) => setConfirmPassword(e.target.value)}
                          required
                        />
                        <button
                          type="button"
                          onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                          className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white transition-colors"
                          style={{ height: '100%', alignContent: 'center', backgroundColor: 'transparent' }}
                        >
                          {showConfirmPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                        </button>
                        {confirmPassword.length > 0 && (
                          <div className={`absolute right-10 top-1/2 -translate-y-1/2 text-sm font-black ${password === confirmPassword ? "text-green-500" : "text-red-500"
                            }`}>
                            {password === confirmPassword ? "✓" : "✗"}
                          </div>
                        )}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>

                <div className="pt-2">
                  <button
                    type="submit"
                    disabled={loading}
                    className="w-full relative group overflow-hidden py-3.5 rounded-xl bg-gradient-to-r from-primary to-accent text-white font-black hover:shadow-lg hover:shadow-primary/30 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                  >
                    <span className="relative z-10">{loading ? "Processing..." : isLogin ? (t("login") || "Login") : (t("register") || "Register")}</span>
                    {!loading && (
                      <ArrowRight size={18} className="relative z-10 group-hover:translate-x-1 transition-transform" />
                    )}
                  </button>
                </div>
              </form>

              <div className="mt-8 text-center border-t border-white/5 pt-6">
                <p className="text-slate-400 text-sm font-medium">
                  {isLogin ? "Don't have an account?" : "Already have an account?"}{" "}
                  <button
                    onClick={() => { setIsLogin(!isLogin); setErrorMsg(""); }}
                    className="text-primary font-bold hover:underline transition-all"
                  >
                    {isLogin ? (t("register") || "Register") : (t("login") || "Login")}
                  </button>
                </p>
              </div>
            </div>
          </motion.div>
        </section>

        {/* Right Side: Market Showcase */}
        <section className="w-full lg:w-1/2 flex p-6 lg:p-12 flex-col justify-center relative mt-8 lg:mt-0 pb-20 lg:pb-12">
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ type: "spring", damping: 25, stiffness: 120, delay: 0.1 }}
            className="w-full max-w-lg mx-auto"
          >
            <div className="hidden sm:block mb-10 text-center lg:text-left">
              <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white mb-4 leading-tight bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">
                {t("tradeWithPrecision") || "Trade with"}<br className="sm:block" />{t("unprecedentedPrecision") || "unprecedented precision."}
              </h2>
              <p className="text-slate-400 text-sm sm:text-base lg:text-lg max-w-md mx-auto lg:mx-0">
                {t("experienceLowestLatency") || "Experience lowest latency execution, advanced charting tools, and high-frequency capabilities."}
              </p>
            </div>

            {/* Simulated Live Market Cards */}
            <div className="space-y-4">
              <div className="flex items-center justify-between text-xs font-bold text-slate-500 uppercase tracking-widest px-4 mb-2">
                <span>{t("trendingMarkets") || "Trending Markets"}</span>
                <span className="flex items-center gap-1 text-green-500"><Activity size={14} /> {t("live") || "Live"}</span>
              </div>

              {MARKET_DATA.map((market, idx) => (
                <motion.div
                  key={market.symbol}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.2 + (idx * 0.1) }}
                  className="glass-card bg-slate-900/40 border border-white/5 p-4 rounded-2xl flex items-center justify-between hover:bg-slate-900/60 transition-colors cursor-default"
                >
                  <div className="flex items-center gap-4">
                    <div className={`w-10 h-10 rounded-xl flex items-center justify-center font-black text-white ${market.isUp ? 'bg-green-500/20' : 'bg-red-500/20'} overflow-hidden p-1.5`}>
                      <img src={market.icon} alt={market.symbol} className="w-full h-full object-contain" />
                    </div>
                    <div>
                      <p className="text-white font-black">{market.symbol}</p>
                      <p className="text-xs text-slate-400 font-semibold">{t(market.name.toLowerCase()) || market.name}</p>
                    </div>
                  </div>

                  {/* Tiny SVG Chart */}
                  <div className="w-24 h-10 opacity-70">
                    <svg viewBox="0 0 100 50" className="w-full h-full preserve-3d overflow-visible">
                      <motion.polyline
                        initial={{ pathLength: 0 }}
                        animate={{ pathLength: 1 }}
                        transition={{ duration: 1.5, ease: "easeInOut" }}
                        fill="none"
                        stroke={market.isUp ? "#22c55e" : "#ef4444"}
                        strokeWidth="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        points={market.points}
                      />
                    </svg>
                  </div>

                  <div className="text-right">
                    <p className="text-white font-mono font-bold">${market.price}</p>
                    <p className={`text-xs font-black flex items-center justify-end gap-1 ${market.isUp ? 'text-green-500' : 'text-red-500'}`}>
                      {market.isUp ? <TrendingUp size={12} /> : <TrendingDown size={12} />}
                      {market.change}
                    </p>
                  </div>
                </motion.div>
              ))}
            </div>

            <div className="mt-8 flex gap-2 sm:gap-3 text-[10px] sm:text-xs md:text-sm font-bold text-slate-500 justify-center w-full flex-wrap max-w-lg mx-auto">
              <span className="flex items-center gap-1 sm:gap-1.5"><ShieldCheck size={14} className="text-primary" /> {t("secure") || "Secure"}</span>
              <span className="hidden sm:inline">•</span>
              <span>{t("fastExecution") || "Fast Execution"}</span>
              <span className="hidden sm:inline">•</span>
              <span>{t("support247") || "24/7 Support"}</span>
            </div>

          </motion.div>
        </section>
      </main>
    </div>
  );
};

const AuthInput: React.FC<{
  icon: React.ReactNode;
  placeholder: string;
  type: string;
  value?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  required?: boolean;
}> = ({ icon, placeholder, type, value, onChange, required }) => (
  <div className="relative group w-full">
    <div className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-primary transition-colors pointer-events-none z-10">
      {icon}
    </div>
    <input
      type={type}
      placeholder={placeholder}
      value={value}
      onChange={onChange}
      required={required}
      className="w-full bg-slate-950/50 border border-white/10 rounded-xl py-3.5 pl-12 pr-12 text-white text-sm font-medium focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary/50 transition-all placeholder:text-slate-600 hover:border-white/20 hover:bg-slate-900/60"
    />
  </div>
);
